export { Deck } from './Deck';
export { Slide } from './Slide';
export { JsonDeck } from './JsonDeck';
export { useStep, useAutoScaling } from './hooks';
export { useDeck } from './DeckContext';
export type { DeckContextType } from './DeckContext';
export { DeckControls } from './DeckControls';
export type { DeckTheme } from './theme';
export { defaultTheme } from './theme';
export { themes } from './themes';
export type { Plugin } from './types';
export { LaserPointer } from './plugins/LaserPointer';
export { PresenterConsole } from './PresenterConsole';
export { Notes } from './notes';
export { Split } from './layouts/Split';
export { SplitSlide } from './layouts/SplitSlide';
export { TitleSlide } from './layouts/TitleSlide';
export { SectionSlide } from './layouts/SectionSlide';
export { BulletsSlide } from './layouts/BulletsSlide';
export { CodeSlide } from './layouts/CodeSlide';
export { SlideLayout } from './layouts/SlideLayout';
export { Code } from './blocks/Code';
export { SlideFactory } from './components/SlideFactory';
export type { LayoutType, SlideData, DeckData } from './schema';